name: Deploy
on: [ push ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build
        run: yarn build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "spa-stc-spartan-daily"
          entrypoint: "./server/entry.mjs"
          root: "dist"
